let userId;
let userRef;
let messageRef;
let snapshotV;
let owner;
let online;
let subStringId;
let subString;
let clicked;
let nameRef;
let aMessage = "";
let reload = 0;
let nameTaken = [];
let allNames = [];
let userName = createName();
let signUpButton = document.querySelector('#sign-up');
let name = document.querySelector('#name');
let body = document.getElementById("body");
let messageInput = document.querySelector('#message-felid');
let sendMessage = document.querySelector('#send');